rpc:
  url: https://1.rpc.thirdweb.com

api:
  basicAuth:
    username: admin
    password: admin
  thirdweb:
    clientId: 123abc

storage:
  main:
    clickhouse:
      host: localhost
      username: admin
      password: password
  staging:
    clickhouse:
      host: localhost
      username: admin
      password: password